### PR TITLE
OpenCV and FFMPEG binaries

### PR DESCRIPTION
**Pull request by a-pasquale**
This includes the opencv.js build from https://github.com/ganwenyao/opencv_js for AruCo marker recognition and uses the ffbinaries package to download ffmpeg binaries for the appropriate platform. 

Photos are currently being stored to the default pictures location and videos to the default video location for your OS. Future feature could be the ability to configure this. 

Video is captured from the canvas using MediaRecorder API as webm and converted to mp4 container using ffmpeg for broader compatibility outside the browser.

### CODE REVIEW

**Comment by tgb20** [comment]
No video appears when I build this branch and errors popup about the ffmepg binaries on a loop. Tried on both my laptop and desktop computer. 
Screen Shot 2020-04-03 at 1 54 53 PM

**Comment by a-pasquale** [comment]
Can you try this? I think I've got the ffmpeg path working with the bundled version.

**Comment by tgb20** [comment]
It not longer says downloading ffmpeg, or a success/failure message. It just says "starting ffmpeg". The error above still appears, and still no video.

**Comment by a-pasquale** [comment]
Can you check what the path for the ffmpeg binary is? It should be
generated dynamically based on how you are running the app in main.js.

I added a VS Code debugging configuration in launch.json.

For later reference, you can inspect the main.js process of a built
electron app with these commands:
lldb /path/to/Hermes.app
run --remote-debugging-port=8315

**Comment by a-pasquale** [comment]
I replaced opencv.js with js-aruco, added an option to label markers with custom strings, added support for multiple start blocks, and added electron-notarize. 

Also includes blocks to take photos, record video, and detect markers. Sensing block to detect whether the drone is flying doesn't currently work.

**Comment by a-pasquale** [comment]
There is also an option to use a local camera instead of the drone camera. This is maybe only useful for testing the AruCo markers and could probably go away eventually, or maybe it's useful for others testing the markers as well?

**Pull request merged**
